/**
 * Derive contrast-requirements.apca.json from the WCAG contract and today's WCAG
 * dark output: each rule's APCA minimum is the lowest Lc its pairs actually reach
 * in that theme, rounded down to a whole number. The APCA contract therefore
 * reproduces the approved dark theme as closely as possible, then applies the same
 * perceptual targets to light mode.
 *
 * The APCA spec clips contrast below about Lc 10 to 0. Rules measuring below
 * LOW_CLIP_LC (faint panels, the scrollbar track) are marked `apcaLowClip: false`
 * and measured with the unclipped formula, so the contract stays fully APCA.
 *
 * Pure and browser-safe; the CLI that writes the file is src/derive-apca-cli.ts.
 */
import { contrast } from "./color.ts";
import { expandRelationships } from "./contract.ts";
import { generateTheme } from "./solve.ts";
import { TARGETS, type ContrastContract, type ContrastRule, type Target, type ThemeRecipe } from "./types.ts";

const LOW_CLIP_LC = 15;

export function deriveApcaContract(recipe: ThemeRecipe, wcag: ContrastContract): ContrastContract {
  if (wcag.algorithm !== "WCAG2") throw new Error("Source contract must be WCAG2");
  const colorsByTarget = Object.fromEntries(TARGETS.map((target) =>
    [target, generateTheme(recipe, wcag, "dark", {}, target).report]));

  const relationships = wcag.relationships.map((rule): ContrastRule => {
    if (rule.contrast === null) return { ...rule };
    const clipped = Math.floor(Math.min(...measured(rule, wcag, colorsByTarget, true)));
    if (clipped >= LOW_CLIP_LC) return { ...rule, contrast: clipped };
    // Too faint for the clipped formula: use raw Lc, keeping one decimal (these are small).
    const raw = Math.floor(Math.min(...measured(rule, wcag, colorsByTarget, false)) * 10) / 10;
    return { ...rule, contrast: raw, apcaLowClip: false };
  });

  return {
    ...wcag,
    algorithm: "APCA",
    semantics: {
      ...wcag.semantics,
      contrast: "Required minimum APCA Lc (absolute value, text on background). null explicitly means no contrast requirement.",
      derivation: "Generated by src/derive-apca.ts from contrast-requirements.json: each minimum is the lowest Lc its pairs reach in the WCAG dark theme, rounded down. Do not edit by hand.",
      apcaLowClip: `Rules with apcaLowClip false use the APCA formula without its low clip, because the spec reports near-background contrast (below about Lc 10) as 0. Such values place faint surfaces; they carry no readability meaning.`,
    },
    relationships,
  };
}

/** APCA Lc of every pair a rule produces, in every target where it applies. */
function measured(rule: ContrastRule, wcag: ContrastContract, reports: Record<string, { selected: Record<string, { hex: string }> }>, lowClip: boolean): number[] {
  const values: number[] = [];
  for (const target of rule.targets ?? TARGETS) {
    const colors = reports[target as Target].selected;
    for (const pair of expandRelationships({ ...wcag, relationships: [rule] })) {
      // Proposed tokens render as their fallback in the current target.
      const token = target === "current" ? wcag.tokens[pair.token].proposed?.fallback ?? pair.token : pair.token;
      if (!colors[token] || !colors[pair.background]) continue;
      values.push(contrast(colors[token].hex, colors[pair.background].hex, "APCA", lowClip));
    }
  }
  if (values.length === 0) throw new Error(`No rendered pairs for rule ${rule.token}`);
  return values;
}
