/**
 * Derive contrast-requirements.apca.json from the WCAG contract and today's WCAG
 * dark output: each rule's APCA minimum is the lowest Lc its pairs actually reach
 * in that theme, rounded down to a whole number. The APCA contract therefore
 * reproduces the approved dark theme as closely as possible, then applies the same
 * perceptual targets to light mode.
 *
 * The APCA spec clips contrast below about Lc 10 to 0. Rules measuring below
 * LOW_CLIP_LC (faint panels, the scrollbar track) are marked `apcaLowClip: false`
 * and measured with the unclipped formula, so the contract stays fully APCA.
 *
 * Pure and browser-safe; the CLI that writes the file is src/derive-apca-cli.ts.
 */
import { contrast } from "./color.ts";
import { expandRelationships } from "./contract.ts";
import { generateTheme } from "./solve.ts";
import { TARGETS, type ContrastContract, type ContrastRule, type Mode, type Target, type ThemeRecipe } from "./types.ts";

const LOW_CLIP_LC = 15;

export function deriveApcaContract(recipe: ThemeRecipe, wcag: ContrastContract): ContrastContract {
  if (wcag.algorithm !== "WCAG2") throw new Error("Source contract must be WCAG2");
  const reportsFor = (mode: Mode) => Object.fromEntries(TARGETS.map((target) =>
    [target, generateTheme(recipe, wcag, mode, {}, target).report]));
  const reports = { dark: reportsFor("dark"), light: reportsFor("light") };

  const relationships = wcag.relationships.map((rule): ContrastRule => {
    const { apcaLightContrast, lightContrast: _wcagLight, ...base } = rule;
    if (rule.contrast === null) return { ...base };
    const lowest = (mode: Mode, lowClip: boolean) => Math.min(...measured(rule, wcag, reports[mode], lowClip));
    // Faint rules (panels, scrollbar track) use the unclipped formula in both modes.
    const clipped = lowest("dark", true) >= LOW_CLIP_LC && (apcaLightContrast ?? lowest("light", true)) >= LOW_CLIP_LC;
    const round = (value: number) => clipped ? Math.floor(value) : Math.floor(value * 10) / 10;
    const dark = round(lowest("dark", clipped));
    const light = apcaLightContrast ?? round(lowest("light", clipped));
    return { ...base, contrast: dark, ...(light !== dark && { lightContrast: light }), ...(!clipped && { apcaLowClip: false }) };
  });

  return {
    ...wcag,
    algorithm: "APCA",
    semantics: {
      ...wcag.semantics,
      contrast: "Required minimum APCA Lc (absolute value, text on background). null explicitly means no contrast requirement.",
      lightContrast: "Light-mode APCA minimum.",
      derivation: "Generated by src/derive-apca-cli.ts from contrast-requirements.json: dark minimums are the lowest Lc each rule's pairs reach in the WCAG dark theme, rounded down; light minimums are apcaLightContrast where set, otherwise measured the same way from the WCAG light theme. Do not edit by hand.",
      apcaLowClip: `Rules with apcaLowClip false use the APCA formula without its low clip, because the spec reports near-background contrast (below about Lc 10) as 0. Such values place faint surfaces; they carry no readability meaning.`,
    },
    relationships,
  };
}

/** APCA Lc of every pair a rule produces, in every target where it applies. */
function measured(rule: ContrastRule, wcag: ContrastContract, reports: Record<string, { selected: Record<string, { hex: string }> }>, lowClip: boolean): number[] {
  const values: number[] = [];
  for (const target of rule.targets ?? TARGETS) {
    const colors = reports[target as Target].selected;
    for (const pair of expandRelationships({ ...wcag, relationships: [rule] })) {
      // Proposed tokens render as their fallback in the current target.
      const token = target === "current" ? wcag.tokens[pair.token].proposed?.fallback ?? pair.token : pair.token;
      if (!colors[token] || !colors[pair.background]) continue;
      values.push(contrast(colors[token].hex, colors[pair.background].hex, "APCA", lowClip));
    }
  }
  if (values.length === 0) throw new Error(`No rendered pairs for rule ${rule.token}`);
  return values;
}
